version: "2.3"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    image: azimu/data-exporter:latest
    # command: ["tail", "-f", "/dev/null"]
    restart: "no"
    env_file: .docker.env
